import { User, Event, RSVP, ChatMessage, TeammatePost, Campus } from './types'

export const campuses: Campus[] = [
  { id: '1', name: 'RMIT University', domain: 'student.rmit.edu.au' },
  { id: '2', name: 'University of Melbourne', domain: 'student.unimelb.edu.au' },
  { id: '3', name: 'Monash University', domain: 'student.monash.edu' },
  { id: '4', name: 'Swinburne University', domain: 'student.swinburne.edu.au' },
]

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Alex Chen',
    email: 'alex.chen@student.rmit.edu.au',
    campus: 'RMIT University',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    interests: ['Tech', 'Gaming', 'Hackathon'],
    vibePoints: 150,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Sarah Kim',
    email: 'sarah.kim@student.unimelb.edu.au',
    campus: 'University of Melbourne',
    avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    interests: ['Food', 'Cultural', 'Wellness'],
    vibePoints: 89,
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    name: 'Marcus Johnson',
    email: 'marcus.johnson@student.monash.edu',
    campus: 'Monash University',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    interests: ['Sports', 'Career', 'Tech'],
    vibePoints: 203,
    createdAt: new Date('2024-01-10'),
  },
]

export const mockEvents: Event[] = [
  {
    id: '1',
    title: '🎮 Gaming Night: Valorant Tournament',
    description: 'Join us for an epic Valorant tournament! Prizes for top 3 teams. Pizza and drinks provided. All skill levels welcome!',
    category: 'Gaming',
    date: new Date('2024-02-15T18:00:00'),
    time: '6:00 PM',
    endDate: new Date('2024-02-15T22:00:00'),
    endTime: '10:00 PM',
    campus: 'RMIT University',
    location: 'Building 80, Level 3, Computer Lab',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=400&fit=crop',
    host: {
      id: 'club-1',
      name: 'RMIT Gaming Society',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
      university: 'RMIT University'
    },
    attendees: ['user-1', 'user-2', 'user-3'],
    maxAttendees: 50,
    isFree: true,
    tags: ['Gaming', 'Tournament', 'Pizza'],
    requirements: [],
    hasFood: true,
    createdBy: 'club-1',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: '2',
    title: '🍜 Dumpling Cook-Off Workshop',
    description: 'Learn to make authentic Chinese dumplings from scratch! All ingredients provided. Vegetarian options available.',
    category: 'Food',
    date: new Date('2024-02-18T14:00:00'),
    time: '2:00 PM',
    endDate: new Date('2024-02-18T17:00:00'),
    endTime: '5:00 PM',
    campus: 'University of Melbourne',
    location: 'Student Union Kitchen, Ground Floor',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=400&fit=crop',
    host: {
      id: '2',
      name: 'Sarah Kim',
      avatar: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face',
      university: 'University of Melbourne'
    },
    attendees: ['user-4', 'user-5'],
    maxAttendees: 20,
    isFree: true,
    tags: ['Cooking', 'Cultural', 'Workshop'],
    requirements: [],
    hasFood: true,
    createdBy: '2',
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-01-28'),
  },
  {
    id: '3',
    title: '🛠 React Native Workshop: Build Your First App',
    description: 'Hands-on workshop to build a mobile app with React Native. Laptops provided. Perfect for beginners!',
    category: 'Tech',
    date: new Date('2024-02-20T10:00:00'),
    time: '10:00 AM',
    endDate: new Date('2024-02-20T16:00:00'),
    endTime: '4:00 PM',
    campus: 'RMIT University',
    location: 'Building 14, Level 2, Lab 14.2.1',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=400&fit=crop',
    host: {
      id: 'club-2',
      name: 'RMIT Tech Society',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
      university: 'RMIT University'
    },
    attendees: ['user-6', 'user-7', 'user-8'],
    maxAttendees: 30,
    isFree: true,
    tags: ['Programming', 'Mobile', 'Workshop'],
    requirements: [],
    hasFood: false,
    createdBy: 'club-2',
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-01-30'),
  },
  {
    id: '4',
    title: '🧪 48-Hour Hackathon: Climate Solutions',
    description: 'Build innovative solutions for climate change. $5000 in prizes! Free meals, snacks, and swag. Form teams of 2-4.',
    category: 'Hackathon',
    date: new Date('2024-02-25T09:00:00'),
    time: '9:00 AM',
    endDate: new Date('2024-02-27T17:00:00'),
    endTime: '5:00 PM',
    campus: 'Monash University',
    location: 'Clayton Campus, Building 10, Innovation Hub',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=400&fit=crop',
    host: {
      id: 'external-1',
      name: 'ClimateTech Melbourne',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
      university: 'Monash University'
    },
    attendees: ['user-9', 'user-10', 'user-11'],
    maxAttendees: 100,
    isFree: true,
    tags: ['Hackathon', 'Climate', 'Prize'],
    requirements: [],
    hasFood: true,
    createdBy: 'external-1',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '5',
    title: '🏃‍♀️ Campus Fun Run & Wellness Fair',
    description: '5K fun run around campus followed by wellness activities. Free t-shirt and healthy snacks!',
    category: 'Wellness',
    date: new Date('2024-02-22T08:00:00'),
    time: '8:00 AM',
    endDate: new Date('2024-02-22T12:00:00'),
    endTime: '12:00 PM',
    campus: 'Swinburne University',
    location: 'Main Campus, Starting at Student Union',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=400&fit=crop',
    host: {
      id: 'club-3',
      name: 'Swinburne Wellness Club',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
      university: 'Swinburne University'
    },
    attendees: ['user-14', 'user-15', 'user-16'],
    maxAttendees: 200,
    isFree: true,
    tags: ['Fitness', 'Wellness', 'Community'],
    requirements: [],
    hasFood: true,
    createdBy: 'club-3',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
]

export const mockChatMessages: Record<string, ChatMessage[]> = {
  '1': [
    {
      id: '1',
      eventId: '1',
      senderId: '1',
      senderName: 'Alex Chen',
      text: 'Hey everyone! Excited for the tournament 🎮',
      createdAt: new Date('2024-02-10T10:30:00'),
    },
    {
      id: '2',
      eventId: '1',
      senderId: '2',
      senderName: 'Sarah Kim',
      text: 'Same! What rank are you?',
      createdAt: new Date('2024-02-10T10:32:00'),
    },
    {
      id: '3',
      eventId: '1',
      senderId: '1',
      senderName: 'Alex Chen',
      text: 'Gold 2, you?',
      createdAt: new Date('2024-02-10T10:33:00'),
    },
  ],
  '2': [
    {
      id: '4',
      eventId: '2',
      senderId: '2',
      senderName: 'Sarah Kim',
      text: 'Welcome to the dumpling workshop! 🥟',
      createdAt: new Date('2024-02-12T09:00:00'),
    },
    {
      id: '5',
      eventId: '2',
      senderId: '3',
      senderName: 'Marcus Johnson',
      text: 'Can\'t wait to learn! Never made dumplings before',
      createdAt: new Date('2024-02-12T09:05:00'),
    },
  ],
}

export const mockTeammatePosts: Record<string, TeammatePost[]> = {
  '4': [
    {
      id: '1',
      eventId: '4',
      title: 'Looking for Frontend Developer',
      description: 'Need someone experienced with React/Next.js for our climate dashboard project',
      skillsNeeded: ['React', 'Next.js', 'TypeScript', 'UI/UX'],
      authorId: '1',
      authorName: 'Alex Chen',
      createdAt: new Date('2024-02-10T14:00:00'),
    },
    {
      id: '2',
      eventId: '4',
      title: 'Data Science Team - 2 spots left',
      description: 'Building ML models for carbon footprint tracking. Need Python and ML experience',
      skillsNeeded: ['Python', 'Machine Learning', 'Data Analysis'],
      authorId: '2',
      authorName: 'Sarah Kim',
      createdAt: new Date('2024-02-11T16:30:00'),
    },
  ],
}

export const mockRSVPs: RSVP[] = [
  { id: '1', eventId: '1', userId: '1', createdAt: new Date('2024-02-01'), checkedIn: false },
  { id: '2', eventId: '1', userId: '2', createdAt: new Date('2024-02-02'), checkedIn: false },
  { id: '3', eventId: '2', userId: '2', createdAt: new Date('2024-02-03'), checkedIn: false },
  { id: '4', eventId: '2', userId: '3', createdAt: new Date('2024-02-04'), checkedIn: false },
  { id: '5', eventId: '3', userId: '1', createdAt: new Date('2024-02-05'), checkedIn: false },
  { id: '6', eventId: '4', userId: '1', createdAt: new Date('2024-02-06'), checkedIn: false },
  { id: '7', eventId: '4', userId: '2', createdAt: new Date('2024-02-07'), checkedIn: false },
  { id: '8', eventId: '5', userId: '3', createdAt: new Date('2024-02-08'), checkedIn: false },
]

// Current user (mock logged in user)
export const currentUser: User = mockUsers[0]
